language: android # project in Android environment
jdk:
   - oraclejdk8
android:
   components:
      - tools # latest version of Android SDK tools
      - platform-tools # ' '
      - build-tools-25.0.2 # build tools version of our project
      - android-25
      - add-on
      - extra
   licenses:
      - 'android-sdk-preview-licesnse-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
